import http from './http'

export const login = data => http.post('/user/login', data)
export const register = data => http.post('/user/register', data)
export const profile = () => http.get('/user/profile')
export const publicUser = id => http.get(`/user/public/${id}`)
export const adminUsers = () => http.get('/user/admin/users')
export const adminCreateUser = data => http.post('/user/admin/users', data)
export const adminUpdateUser = (id, data) => http.put(`/user/admin/users/${id}`, data)
export const adminDeleteUser = id => http.delete(`/user/admin/users/${id}`)

export const hotSkills = () => http.get('/skill/hot')
export const pageSkills = params => http.get('/skill/page', { params })
export const searchSkills = keyword => http.get('/skill/search', { params: { keyword } })
export const skillDetail = id => http.get(`/skill/${id}`)
export const publishSkill = data => http.post('/skill', data)
export const updateSkill = (id, data) => http.put(`/skill/${id}`, data)
export const deleteSkill = id => http.delete(`/skill/${id}`)
export const userSkills = userId => http.get(`/skill/user/${userId}`)

export const requestHall = () => http.get('/order/requests')
export const adminRequests = () => http.get('/order/admin/requests')
export const requestDetail = id => http.get(`/order/requests/${id}`)
export const publishRequest = data => http.post('/order/requests', data)
export const updateRequest = (id, data) => http.put(`/order/requests/${id}`, data)
export const deleteRequest = id => http.delete(`/order/requests/${id}`)
export const userRequests = userId => http.get(`/order/requests/user/${userId}`)
export const acceptRequest = (id, acceptUserId) => http.put(`/order/requests/${id}/accept`, null, { params: { acceptUserId } })
export const createOrder = data => http.post('/order/orders', data)
export const userOrders = userId => http.get(`/order/orders/user/${userId}`)
export const adminOrders = () => http.get('/order/admin/orders')
export const acceptOrder = (id, sellerId) => http.put(`/order/orders/${id}/accept`, null, { params: { sellerId } })
export const confirmOrder = (id, buyerId) => http.put(`/order/orders/${id}/confirm`, null, { params: { buyerId } })
export const finishOrder = (id, sellerId) => http.put(`/order/orders/${id}/finish`, null, { params: { sellerId } })
export const updateOrderStatus = (id, status) => http.put(`/order/orders/${id}/status`, null, { params: { status } })
export const createComment = data => http.post('/order/comments', data)
export const userComments = userId => http.get(`/order/comments/user/${userId}`)
export const adminComments = () => http.get('/order/admin/comments')
export const deleteComment = id => http.delete(`/order/comments/${id}`)

export const messages = userId => http.get('/message', { params: { userId } })
export const adminMessages = () => http.get('/message/admin/all')
export const readMessage = id => http.put(`/message/${id}/read`)
export const deleteMessage = id => http.delete(`/message/${id}`)
